### PR TITLE
Add bottom margin to lists

### PR DESCRIPTION
**Pull request by adillari**
Title

### CODE REVIEW

**Comment by adillari** [comment]
Screenshot from 2024-08-31 21-59-05
Screenshot from 2024-08-31 21-58-43
Screenshot from 2024-08-31 21-58-38
Screenshot from 2024-08-31 21-58-30
@dylhack

**Comment by dylhack** [comment]
Thanks for this contribution :) @adillari, there's one more list at https://github.com/dylhack/trackboard/blob/83d025e0972f47e29cf611fbbde2093140e3032a/app/views/users/show.html.erb#L36-L43

**Comment by adillari** [comment]
ced1b25c1190f33bca43faff8900016fc3d70fa3
@dylhack 
Got the users index as well which had same issue

**Review by dylhack — APPROVED** [review]
:raised_hands:

**Pull request merged**
